### ISSUE TITLE
bug: when trying to open book with no cover

### ISSUE THREAD

**Issue by Ke-abr** [Ke-abr/ebooks#1]
Example: Le pot au rose by Dominique Bertrand

```
UndefinedError
jinja2.exceptions.UndefinedError: 'None' has no attribute 'split'

Traceback (most recent call last)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
File "/home/freedfox/git/ebooks/ebook_webapp/app.py", line 68, in book_detail
return render_template('book.html', ebook=ebook)
File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 150, in render_template
return _render(app, template, context)
File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 131, in _render
rv = template.render(context)
File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/home/freedfox/git/ebooks/ebook_webapp/templates/book.html", line 1, in top-level template code
{% extends "base.html" %}
File "/home/freedfox/git/ebooks/ebook_webapp/templates/base.html", line 22, in top-level template code
{% block content %}{% endblock %}Open an interactive python shell in this frame
File "/home/freedfox/git/ebooks/ebook_webapp/templates/book.html", line 7, in block 'content'
<img src="{{ url_for('static', filename=ebook.cover_path.split('static/')[-1]) }}" alt="Cover" class="ebook-cover">
File "/usr/local/lib/python3.10/dist-packages/jinja2/utils.py", line 83, in from_obj
if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'split'
```

**Comment by Ke-abr** [comment]
Handled by providing a default cover
